name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Coding Standard
        run: composer cs

      - name: Rector (dry-run)
        run: composer rector:dry

      - name: PHPStan
        run: composer stan

  tests:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run tests
        run: composer test

  mutation:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push' # np. tylko na push
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Infection
        run: composer infection
